language: java
addons:
  sonarcloud:
    organization: "davidgfolch-github"
    token:
      secure: "YYdOsCEj3PTKo8qBFV7mwo7FAhThUKBv7WiBlv5sJLA1ReWS7K+WMb5gHGT3K1M5o2QbPfq7kw4+ivKMH5s3ZLR9fLqhvFgKWLWOztjM/lxm5BN393a4ieYhrjVrfavs50hp1H9vsy4RLv3QG8yWMO4siGLq7RGDjXxqFTFRt3my1Z2CPKsWSDv7SBRnWi5d4aRRnUOFscAidgdLbax0rreScR67e2Ud63+YPa+jivPpStEDrU0agdrUdEeilwFhT8d9d56j2ppoohyoHmwRdgGCqkf8pR5fCwSSz15PPqnBqe5mhG/JRCy1XqA9LoIS/oXbX0+u0akO3zU1XDj1HIJ/53vZ0tioij7XKOyCwr0oxJEGMut/KhXwITOd+HwBUZ2/ae7rxIC4SfI8uB679IjPRQ7bv0IL9RpIkfue3n27XzcR0dX8dBDGgWg/W8cnF3qpTpsdLZR/yHtPw8jQPssHZV47YfwxEKCPlLveEG1pQu+QB+7DRnVREJLOvTbvEETJ11bhqT+Yu+ajKIvZDHglDh3scfsxqNQZuDBIrPnkNetx/E3mtXy6t1PzB4LR/Y8nLrXCGG1HFW8vdYe9f3FFT4XfjIcG43bR5Vgdkj2cLtxTVAp8LdESKGd9XJT1F5T1fEsHCzvYpfIxwUlrSMEo7AOcb6bnu7y+m2iz1sM=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar